{% set name = "dask-cuda" %}
{% set version = "23.6.230607" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask-cuda-{{ version }}.tar.gz
  sha256: 527c1e1d391d7f672963848f137effbdd89ba8b98558b1d5079ff68ea5456283

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dask-cuda-worker = dask_cuda.cli:worker
    - dask-cuda-config = dask_cuda.cli:config

requirements:
  host:
    - python >=3.9
    - setuptools >=64.0.0
      # tomli should be less py<3.11
    - tomli
    - versioneer >=0.24
    - pip
  run:
    - python >=3.9
    - dask-core ==2023.3.2
    - distributed ==2023.3.2.1
    - dask ==2023.3.2
    - pynvml >=11.0.0,<11.5
    - numpy >=1.21
    - numba >=0.57
    - pandas >=1.3,<1.6.0dev0
    - zict >=2.0.0
    - __linux

test:
  imports:
    - dask_cuda
    - dask_cuda.benchmarks
  commands:
    - pip check
    # Old entry points
    - dask-cuda-worker --help
    - dask-cuda-config --help
    # New entry points
    - dask cuda --help
    - dask cuda worker --help
    - dask cuda config --help
  requires:
    - pip

about:
  home: https://github.com/rapidsai/dask-cuda
  summary: Utilities for Dask and CUDA interactions
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
