{% set name = "dask-cuda" %}
{% set version = "24.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0d6fdb90de1694d5a157967a37703adf8910aea948d5cbaa59fe55ba06376b4f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dask-cuda-worker = dask_cuda.cli:worker
    - dask-cuda-config = dask_cuda.cli:config

requirements:
  host:
    - python >=3.9
    - setuptools >=64.0.0
      # tomli should be less py<3.11
    - tomli
    - pip
  run:
    - click >=8.1
    - rapids-dask-dependency ==24.6.*
    - python >=3.9
    - dask-core ==2023.9.2
    - distributed ==2023.9.2
    - dask ==2023.9.2
    - pynvml <11.5,>=11.0.0
    - numpy <2.0a0,>=1.23
    - numba >=0.57
    - pandas >=1.3
    - zict >=2.0.0
    - __linux

test:
  imports:
    - dask_cuda
    - dask_cuda.benchmarks
  commands:
    - pip check
    # Old entry points
    - dask-cuda-worker --help
    - dask-cuda-config --help
    # New entry points
    - dask cuda --help
    - dask cuda worker --help
    - dask cuda config --help
  requires:
    - pip

about:
  home: https://github.com/rapidsai/dask-cuda
  summary: Utilities for Dask and CUDA interactions
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
