{% set name = "dask-cuda" %}
{% set version = "21.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask-cuda-{{ version }}.tar.gz
  sha256: be793da9156bb5e8f799c679e30c1db418391e7d84497eccbcc31aff2e8c40b1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dask-cuda-worker = dask_cuda.cli.dask_cuda_worker:go

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dask =2021.09.1
    - distributed =2021.09.1
    - numba >=0.53.1
    - numpy >=1.16.0
    - pynvml >=11.0.0

test:
  imports:
    - dask_cuda
    - dask_cuda.benchmarks
  commands:
    - pip check
    - dask-cuda-worker --help
  requires:
    - pip

about:
  home: https://github.com/rapidsai/dask-cuda
  summary: Utilities for Dask and CUDA interactions
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
